const fs = require('fs');
const p = 'src/pages/ClearPathLensPage.tsx';
let txt = fs.readFileSync(p, 'utf8');
if (!txt.includes("Featured Lens Article")) {
  txt = txt.replace(
    /(<div className="lg:col-span-8 space-y-10">)/,
    `$1\n            {/* Featured Lens Article */}\n            <section className="bg-surface-bright border-2 border-primary/20 rounded-2xl p-6 md:p-8 shadow-sm">\n              <div className="flex items-center gap-2 text-xs font-mono font-bold text-primary bg-primary/10 px-3 py-1 rounded-full uppercase tracking-wider mb-6 inline-block">\n                LATEST LENS — {lens.publishedAt}\n              </div>\n\n              <div className="space-y-5">\n                <span className="text-xs font-mono font-bold text-secondary uppercase tracking-wider block">\n                  {lens.topic}\n                </span>\n                <h2 className="text-2xl sm:text-3xl font-black font-serif text-on-surface leading-tight">\n                  <Link to={\`/article/\${lens.slug}\`} className="hover:text-primary transition-colors">\n                    {lens.title}\n                  </Link>\n                </h2>\n                <p className="text-sm text-on-surface-variant leading-relaxed">\n                  {lens.detailedAnalysis}\n                </p>\n\n                <div className="bg-surface-container-low border border-outline-variant/60 rounded-xl p-5 space-y-3 mt-4">\n                  <div className="flex items-center gap-2 mb-2">\n                    <ShieldAlert className="w-4 h-4 text-primary" />\n                    <h3 className="text-sm font-bold text-on-surface font-mono uppercase tracking-wide">\n                      Core Institutional Finding\n                    </h3>\n                  </div>\n                  <p className="text-xs text-on-surface-variant leading-relaxed">\n                    {lens.coreFinding}\n                  </p>\n                </div>\n\n                <div className="pt-2 flex items-center gap-4">\n                  <Link\n                    to={\`/article/\${lens.slug}\`}\n                    className="inline-flex items-center gap-2 px-5 py-2.5 bg-primary hover:bg-primary/90 text-on-primary font-bold text-xs uppercase tracking-wider rounded-xl transition-all"\n                  >\n                    <span>Read Full Analysis</span>\n                    <ArrowRight className="w-4 h-4" />\n                  </Link>\n                </div>\n              </div>\n            </section>\n`
  );
  fs.writeFileSync(p, txt);
}
