const fs = require('fs');
const p = 'src/pages/news/ThePublicRecordPage.tsx';
let txt = fs.readFileSync(p, 'utf8');
if (!txt.includes("Featured Public Record")) {
  txt = txt.replace(
    /(<main[^>]*>)/,
    `$1\n            {/* Featured Public Record */}\n            <section className="bg-surface-bright border-2 border-primary/20 rounded-2xl p-6 md:p-8 shadow-sm relative overflow-hidden">\n              <div className="absolute top-4 right-6 text-primary/10 pointer-events-none">\n                <Quote className="w-28 h-28" />\n              </div>\n\n              <div className="flex items-center gap-2 text-xs font-mono font-bold text-primary bg-primary/10 px-3 py-1 rounded-full uppercase tracking-wider mb-6 inline-block">\n                FEATURED RECORD — {currentRecord.date}\n              </div>\n\n              <div className="space-y-6 relative z-10">\n                <blockquote className="text-lg sm:text-2xl font-serif font-bold text-on-surface leading-snug italic border-l-4 border-primary pl-5 py-2">\n                  "{currentRecord.quote}"\n                </blockquote>\n\n                <div className="bg-surface-container-low border border-outline-variant/60 rounded-xl p-5 space-y-3">\n                  <div>\n                    <h3 className="text-base font-extrabold font-serif text-on-surface">\n                      {currentRecord.speakerName}\n                    </h3>\n                    <p className="text-xs font-semibold text-primary font-mono">\n                      {currentRecord.position}\n                    </p>\n                  </div>\n\n                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-on-surface-variant pt-2 border-t border-outline-variant/40">\n                    <div>\n                      <span className="font-bold text-on-surface block">Setting / Forum:</span>\n                      <span>{currentRecord.setting}</span>\n                    </div>\n                    <div>\n                      <span className="font-bold text-on-surface block">Context:</span>\n                      <span>{currentRecord.context}</span>\n                    </div>\n                  </div>\n                </div>\n\n                <div className="pt-2">\n                  <a\n                    href={currentRecord.sourceLinkUrl}\n                    target="_blank"\n                    rel="noopener noreferrer"\n                    className="inline-flex items-center gap-1.5 text-xs font-bold font-mono text-primary hover:underline"\n                  >\n                    <span>View Original Source</span>\n                    <ExternalLink className="w-3.5 h-3.5" />\n                  </a>\n                </div>\n              </div>\n            </section>\n`
  );
  fs.writeFileSync(p, txt);
}
