const fs = require('fs');

const todaysBriefPath = 'src/pages/news/TodaysBriefPage.tsx';
let tb = fs.readFileSync(todaysBriefPath, 'utf8');
if (!tb.includes("Featured Today's Brief")) {
  tb = tb.replace(
    /(<main[^>]*>)/,
    `$1\n        {/* Featured Today's Brief */}\n        <section className="bg-surface-bright border-2 border-primary/20 rounded-2xl p-6 md:p-8 shadow-sm">\n          <div className="flex flex-wrap items-center justify-between gap-3 pb-4 mb-6 border-b border-outline-variant/60">\n            <span className="text-xs font-mono font-bold text-primary bg-primary/10 px-3 py-1 rounded-full uppercase tracking-wider">\n              FEATURED BRIEF • {CURRENT_DAILY_EDITION.formattedDate}\n            </span>\n            <span className="text-xs font-mono text-on-surface-variant flex items-center gap-1.5">\n              <Clock className="w-3.5 h-3.5 text-primary" />\n              {brief.readingTime}\n            </span>\n          </div>\n\n          <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-start">\n            <div className="md:col-span-7 space-y-4">\n              <span className="text-xs font-mono font-bold text-secondary uppercase tracking-wider block">\n                {brief.category}\n              </span>\n              <h2 className="text-2xl sm:text-3xl font-extrabold font-serif text-on-surface leading-tight">\n                <Link to={\`/article/\${brief.slug}\`} className="hover:text-primary transition-colors">\n                  {brief.title}\n                </Link>\n              </h2>\n              {brief.subtitle && (\n                <p className="text-sm font-medium text-on-surface-variant/90 leading-relaxed">\n                  {brief.subtitle}\n                </p>\n              )}\n\n              <div className="pt-2 flex items-center gap-4">\n                <Link\n                  to={\`/article/\${brief.slug}\`}\n                  className="inline-flex items-center gap-2 px-5 py-2.5 bg-primary hover:bg-primary/90 text-on-primary font-bold text-xs uppercase tracking-wider rounded-xl transition-all"\n                >\n                  <span>Read Full Briefing</span>\n                  <ArrowRight className="w-4 h-4" />\n                </Link>\n              </div>\n            </div>\n\n            <div className="md:col-span-5 rounded-2xl overflow-hidden border border-outline-variant h-56 sm:h-64 relative group">\n              <img\n                src={brief.coverImage}\n                alt={brief.title}\n                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"\n              />\n            </div>\n          </div>\n        </section>\n`
  );
  fs.writeFileSync(todaysBriefPath, tb);
}

const inFocusPath = 'src/pages/news/InFocusPage.tsx';
let inf = fs.readFileSync(inFocusPath, 'utf8');
if (!inf.includes("Lead Featured In Focus Article")) {
  inf = inf.replace(
    /(<main[^>]*>)/,
    `$1\n        {/* Lead Featured In Focus Article */}\n        {leadStory && (\n          <section className="bg-surface-bright border-2 border-primary/20 rounded-2xl p-6 md:p-8 shadow-sm">\n            <div className="flex items-center gap-2 text-xs font-mono font-bold text-primary bg-primary/10 px-3 py-1 rounded-full uppercase tracking-wider mb-4 inline-block">\n              LATEST IN FOCUS ANALYSIS — GOLD #01\n            </div>\n\n            <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-center">\n              <div className="md:col-span-7 space-y-4">\n                <span className="text-xs font-mono font-bold text-secondary uppercase tracking-wider block">\n                  {leadStory.category}\n                </span>\n                <h2 className="text-2xl sm:text-3xl font-black font-serif text-on-surface leading-tight">\n                  <Link to={\`/article/\${leadStory.slug}\`} className="hover:text-primary transition-colors">\n                    {leadStory.title}\n                  </Link>\n                </h2>\n                <p className="text-sm text-on-surface-variant leading-relaxed">\n                  {leadStory.excerpt}\n                </p>\n\n                <div className="pt-2 flex items-center gap-4">\n                  <Link\n                    to={\`/article/\${leadStory.slug}\`}\n                    className="inline-flex items-center gap-2 px-5 py-2.5 bg-primary hover:bg-primary/90 text-on-primary font-bold text-xs uppercase tracking-wider rounded-xl transition-all"\n                  >\n                    <span>Read Full Analysis</span>\n                    <ArrowRight className="w-4 h-4" />\n                  </Link>\n                </div>\n              </div>\n\n              <div className="md:col-span-5 rounded-2xl overflow-hidden border border-outline-variant h-56 sm:h-64 relative group">\n                <img\n                  src={leadStory.coverImage}\n                  alt={leadStory.title}\n                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"\n                />\n              </div>\n            </div>\n          </section>\n        )}\n`
  );
  fs.writeFileSync(inFocusPath, inf);
}

