const fs = require('fs');
const p = 'src/pages/news/SignalsToWatchPage.tsx';
let txt = fs.readFileSync(p, 'utf8');
if (!txt.includes("Timeline of Upcoming Signals")) {
  txt = txt.replace(
    /(<main[^>]*>)/,
    `$1\n        {/* Timeline of Upcoming Signals */}\n        <section className="bg-surface-bright border-2 border-primary/20 rounded-2xl p-6 md:p-8 shadow-sm">\n          <div className="flex items-center justify-between gap-3 pb-4 mb-8 border-b border-outline-variant/60">\n            <span className="text-xs font-mono font-bold text-primary bg-primary/10 px-3 py-1 rounded-full uppercase tracking-wider">\n              UPCOMING CRITICAL SIGNALS TIMELINE\n            </span>\n            <span className="text-xs font-mono text-on-surface-variant flex items-center gap-1">\n              <Calendar className="w-3.5 h-3.5 text-primary" />\n              WEEK AHEAD FORECAST\n            </span>\n          </div>\n\n          <div className="space-y-6">\n            {upcomingSignals.map((sig, idx) => (\n              <div\n                key={sig.id || idx}\n                className="bg-surface-container-low hover:bg-surface-container border border-outline-variant/60 rounded-xl p-5 transition-all"\n              >\n                <div className="grid grid-cols-1 md:grid-cols-12 gap-4 items-start">\n                  <div className="md:col-span-3">\n                    <span className="inline-block px-3 py-1 bg-primary text-on-primary font-mono text-xs font-bold rounded-md uppercase tracking-wider">\n                      {sig.dateOrDay}\n                    </span>\n                  </div>\n\n                  <div className="md:col-span-9 space-y-2">\n                    <h3 className="text-base font-bold font-serif text-on-surface leading-tight">\n                      {sig.event}\n                    </h3>\n                    <p className="text-xs text-on-surface-variant leading-relaxed">\n                      {sig.shortExplanation}\n                    </p>\n\n                    <div className="bg-amber-500/10 border-l-4 border-amber-500 p-3 rounded-r-lg mt-3">\n                      <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-amber-700 dark:text-amber-400 block">\n                        WHY IT MATTERS\n                      </span>\n                      <p className="text-xs font-semibold text-on-surface mt-0.5">\n                        {sig.whyItMatters}\n                      </p>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            ))}\n          </div>\n        </section>\n`
  );
  fs.writeFileSync(p, txt);
}
