const fs = require('fs');
const p = 'src/pages/news/TheIndicatorPage.tsx';
let txt = fs.readFileSync(p, 'utf8');
if (!txt.includes("Featured Current Indicator")) {
  txt = txt.replace(
    /(<main[^>]*>)/,
    `$1\n        {/* Featured Current Indicator */}\n        <section className="bg-surface-bright border-2 border-primary/20 rounded-2xl p-6 md:p-8 shadow-sm">\n          <div className="flex items-center justify-between gap-3 pb-4 mb-6 border-b border-outline-variant/60">\n            <span className="text-xs font-mono font-bold text-primary bg-primary/10 px-3 py-1 rounded-full uppercase tracking-wider">\n              FEATURED INDICATOR — {currentIndicator.publishedAt}\n            </span>\n            <span className="text-xs font-mono text-on-surface-variant flex items-center gap-1">\n              <Database className="w-3.5 h-3.5 text-primary" />\n              VERIFIED RECORD\n            </span>\n          </div>\n\n          <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-center">\n            <div className="md:col-span-5 bg-surface-container-low border border-primary/30 rounded-2xl p-6 flex flex-col items-center justify-center text-center shadow-inner">\n              <span className="text-4xl sm:text-5xl font-black font-mono text-primary tracking-tight mb-2">\n                {currentIndicator.number}\n              </span>\n              <span className="text-xs font-serif font-bold text-on-surface uppercase tracking-wide">\n                {currentIndicator.title}\n              </span>\n            </div>\n\n            <div className="md:col-span-7 space-y-4">\n              <h2 className="text-xl font-bold font-serif text-on-surface">\n                {currentIndicator.title}\n              </h2>\n              <p className="text-xs sm:text-sm text-on-surface-variant leading-relaxed">\n                {currentIndicator.description}\n              </p>\n\n              {/* Why It Matters */}\n              <div className="bg-amber-500/10 border-l-4 border-amber-500 p-3 rounded-r-xl">\n                <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-amber-700 dark:text-amber-400 block mb-1">\n                  WHY IT MATTERS\n                </span>\n                <p className="text-xs font-semibold text-on-surface">\n                  {currentIndicator.whyItMatters}\n                </p>\n              </div>\n\n              <div className="pt-2 flex items-center justify-between">\n                <a\n                  href={currentIndicator.supportingSourceUrl}\n                  target="_blank"\n                  rel="noopener noreferrer"\n                  className="inline-flex items-center gap-1.5 text-xs font-bold font-mono text-primary hover:underline"\n                >\n                  <span>Verify Data Source</span>\n                  <ExternalLink className="w-3.5 h-3.5" />\n                </a>\n              </div>\n            </div>\n          </div>\n        </section>\n`
  );
  fs.writeFileSync(p, txt);
}
